FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

WORKDIR /app/cmd/traffic-ingestor
RUN CGO_ENABLED=0 GOOS=linux go build -o /traffic-ingestor .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /traffic-ingestor .

EXPOSE 8080

CMD ["./traffic-ingestor"]